blank_issues_enabled: true
contact_links:
  - name: Email
    url: mailto:hatrongvu13@gmail.com
    about: Liên hệ trực tiếp qua email.
  - name: LinkedIn
    url: https://www.linkedin.com/in/iamhatrongvu
    about: Kết nối qua LinkedIn.
